name: Testing

on:
  workflow_dispatch:

jobs:
  call-external-workflow:
    uses: DaviMacielCavalcante/empresa-pipelines/.github/workflows/template-build.yaml@main
    with:
      image-tag: 'latest'
      image-name: 'teste-image'
    