name: Testing

on:
  workflow_dispatch:

jobs:
  call-external-workflow:
    uses: DaviMacielCavalcante/empresa-pipelines/.github/workflows/template-build.yaml@main
    with:
      image-tag: 'latest'
      image-name: 'teste-image'
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    